package org.hnau.ktiot.client.projector.utils

data class Localization(
    val app_name: String = "KtIoT",
    val credentials: String = "Авторизация",
    val login: String = "Вход",
    val address: String = "Адрес",
    val addressIsIncorrectError: String = "Некорректный формат адреса",
    val port: String = "Порт",
    val protocol: String = "Протокол",
    val portIsIncorrectError: String = "Некорректный порт",
    val client_id: String = "Идентификатор клиента",
    val clientIdIsEmptyError: String = "Идентификатор клиента не должен быть пустым",
    val user: String = "Пользователь",
    val userIsEmptyError: String = "Имя пользователя не должно быть пустым",
    val password: String = "Пароль",
    val passwordIsEmptyError: String = "Пароль не должен быть пустым",
    val logout: String = "Выход",
    val before_reconnection: String = "До переподключения",
    val reconnect_now: String = "Переподключиться сейчас",
    val connecting: String = "Подключение",
    val connection_error: String = "Ошибка подключения",
    val seconds_short: String = "с",
    val minutes_short: String = "м",
    val hours_short: String = "ч",
    val days_short: String = "д",
    val yes: String = "Да",
    val no: String = "Нет",
)